// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	repo "github.com/restic/rest-server/repo"
	mock "github.com/stretchr/testify/mock"
)

// BlobMetricFunc is an autogenerated mock type for the BlobMetricFunc type
type BlobMetricFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: objectType, operation, nBytes
func (_m *BlobMetricFunc) Execute(objectType string, operation repo.BlobOperation, nBytes uint64) {
	_m.Called(objectType, operation, nBytes)
}

// NewBlobMetricFunc creates a new instance of BlobMetricFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBlobMetricFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *BlobMetricFunc {
	mock := &BlobMetricFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
